import { useState, useEffect, useCallback } from 'react';
import type {
    Player, Ability, ChatLog, GameState, MoveLog, ActionRequest,
    ChatRequest, StateUpdateRequest, RegisterRequest,
} from '../utils/types';
import {
    fetchPlayers, fetchAbilities, fetchChats, fetchGameState, fetchMoveLogs,
} from '../services/fetch_api.ts';
import {
    postAction, postChat, postGameState, postPlayer,
} from '../services/post_api.ts'
import { useWebSocket } from './useWebSocket';

export interface UseGameDataOptions {
    token?: string;
    player?: Player | null;
}

export function useGameData({ token, player }: UseGameDataOptions = {}) {
    // ==========================================
    // Local State Management
    // ==========================================
    const [players, setPlayers] = useState<Player[]>([]);
    const [abilities, setAbilities] = useState<Ability[]>([]);
    const [chats, setChats] = useState<ChatLog[]>([]);
    const [gameState, setGameState] = useState<GameState | null>(null);
    const [moveLogs, setMoveLogs] = useState<MoveLog[]>([]);

    const [isLoading, setIsLoading] = useState<boolean>(true);
    const [error, setError] = useState<string | null>(null);

    // ==========================================
    // Initial Data Fetching (REST API)
    // ==========================================
    const refreshData = useCallback(async () => {
        setIsLoading(true);
        setError(null);
        try {
            // Execute non-authenticated fetches concurrently
            const [abilitiesRes, chatsRes, stateRes, movesRes] = await Promise.all([
                fetchAbilities(),
                fetchChats(),
                fetchGameState(),
                fetchMoveLogs(),
            ]);

            setAbilities(abilitiesRes.data);
            setChats([...chatsRes.data].reverse());
            setGameState(stateRes.data);
            setMoveLogs(movesRes.data);

            // Fetch authenticated data if token exists[cite: 1]
            if (token) {
                const playersRes = await fetchPlayers(token);
                setPlayers(playersRes.data);
            }
        } catch (err: any) {
            setError(err.message || 'Failed to load initial game data');
        } finally {
            setIsLoading(false);
        }
    }, [token]);

    // Run on mount or when token changes
    useEffect(() => {
        refreshData();
    }, [refreshData]);

    // ==========================================
    // Real-Time Subscriptions (WebSocket)
    // ==========================================
    const { isConnected, connect, disconnect } = useWebSocket({
        playerId: player?.id,
        playerName: player?.username,

        // Server broadcasts a player joining the session
        onPlayerJoined: useCallback((newPlayer: Player) => {
            setPlayers((prev) => {
                // Prevent duplicates by filtering out any existing player with the same ID
                const filtered = prev.filter((p) => p.id !== newPlayer.id);
                return [...filtered, newPlayer];
            });
        }, []),

        // Server broadcasts a player leaving/disconnecting
        onPlayerLeft: useCallback((departedPlayer: Player) => {
            setPlayers((prev) => prev.filter((p) => p.id !== departedPlayer.id));
        }, []),

        // Server broadcasts a game state update
        onGameStateUpdated: useCallback((newState: GameState) => {
            setGameState(newState);
        }, []),

        // Server broadcasts a new chat message
        onChatMessageReceived: useCallback((chatMsg: ChatLog) => {
            setChats((prev) => [...prev, chatMsg]);
        }, []),

        // Server broadcasts a combat/movement action
        onActionPerformed: useCallback((result: any) => {
            // Assuming the result payload contains the moveLog generated by the server[cite: 1]
            if (result?.moveLog) {
                setMoveLogs((prev) => [result.moveLog, ...prev]);
            }
        }, []),
    });

    // ==========================================
    // API Mutators (Outgoing Actions)
    // ==========================================

    const registerPlayer = async (data: RegisterRequest) => {
        const res = await postPlayer(data);
        return res.data;
    };

    const performAction = async (data: ActionRequest) => {
        if (!token) throw new Error('Authentication required for actions');
        const res = await postAction(data, token);
        return res.data;
    };

    const sendChat = async (message: string) => {
        if (!token) throw new Error('Authentication required for chat');
        const res = await postChat({ message }, token);
        return res.data;
    };

    const updateGameState = async (data: StateUpdateRequest) => {
        if (!token) throw new Error('Authentication required to update state');
        const res = await postGameState(data, token);

        // Optimistically update the state locally
        setGameState(res.data);
        return res.data;
    };

    return {
        // State
        players,
        abilities,
        chats,
        gameState,
        moveLogs,
        isLoading,
        error,

        // Connection Info
        isWsConnected: isConnected,

        // API Actions
        refreshData,
        registerPlayer,
        performAction,
        sendChat,
        updateGameState,

        // WS Manual Controls
        connectWs: connect,
        disconnectWs: disconnect,
    };
}